# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2020-09-28"
# docker_image = "jjy0/ckb-capsule-recipe-rust:2020-9-28"

# capsule version
version = "0.4.5"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "always"
template_type = "Rust"

[[contracts]]
name = "never"
template_type = "Rust"

[[contracts]]
name = "ckb500"
template_type = "Rust"

[[contracts]]
name = "occlock"
template_type = "Rust"

[[contracts]]
name = "icclock"
template_type = "Rust"

[[contracts]]
name = "hashlock"
template_type = "Rust"

[[contracts]]
name = "counter"
template_type = "Rust"

[[contracts]]
name = "jsoncell"
template_type = "Rust"

[[contracts]]
name = "datacap"
template_type = "Rust"

[[contracts]]
name = "data10"
template_type = "Rust"

[[contracts]]
name = "icctype"
template_type = "Rust"

[[contracts]]
name = "ic3type"
template_type = "Rust"

[[contracts]]
name = "odcounter"
template_type = "Rust"

[[contracts]]
name = "oc5type"
template_type = "Rust"

[[contracts]]
name = "datarange"
template_type = "Rust"

[[contracts]]
name = "doublecounter"
template_type = "Rust"

[[contracts]]
name = "aggcounter"
template_type = "Rust"

[[contracts]]
name = "aggdoublecounter"
template_type = "Rust"
