[package]
name = "jsoncell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.10.0"
lite-json = { version = "0.2.0", default-features = false }
